# Generated by Django 4.1.2 on 2022-10-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cloudp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="类"
                    ),
                ),
                (
                    "up",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="上限"
                    ),
                ),
                (
                    "down",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="下限"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, max_length=50, null=True, verbose_name="分值"
                    ),
                ),
            ],
            options={"verbose_name": "云价格次数", "verbose_name_plural": "云价格次数",},
        ),
        migrations.CreateModel(
            name="Clouds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="类"
                    ),
                ),
                (
                    "up",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="上限"
                    ),
                ),
                (
                    "down",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="下限"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, max_length=50, null=True, verbose_name="分值"
                    ),
                ),
            ],
            options={"verbose_name": "云汉商城情况", "verbose_name_plural": "云汉商城情况",},
        ),
        migrations.CreateModel(
            name="Ic_now",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="类"
                    ),
                ),
                (
                    "up",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="上限"
                    ),
                ),
                (
                    "down",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="下限"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, max_length=50, null=True, verbose_name="分值"
                    ),
                ),
            ],
            options={"verbose_name": "IC网现货数", "verbose_name_plural": "IC网现货数",},
        ),
        migrations.CreateModel(
            name="Ic_same",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="类"
                    ),
                ),
                (
                    "up",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="上限"
                    ),
                ),
                (
                    "down",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="下限"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, max_length=50, null=True, verbose_name="分值"
                    ),
                ),
            ],
            options={"verbose_name": "IC网同行数", "verbose_name_plural": "IC网同行数",},
        ),
        migrations.CreateModel(
            name="Mul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="类"
                    ),
                ),
                (
                    "up",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="上限"
                    ),
                ),
                (
                    "down",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="下限"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, max_length=50, null=True, verbose_name="分值"
                    ),
                ),
            ],
            options={"verbose_name": "倍数", "verbose_name_plural": "倍数",},
        ),
        migrations.CreateModel(
            name="Same_now",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="类"
                    ),
                ),
                (
                    "up",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="上限"
                    ),
                ),
                (
                    "down",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="下限"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, max_length=50, null=True, verbose_name="分值"
                    ),
                ),
            ],
            options={"verbose_name": "同行现货变化", "verbose_name_plural": "同行现货变化",},
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lei",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="类"
                    ),
                ),
                (
                    "up",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="上限"
                    ),
                ),
                (
                    "down",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="下限"
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, max_length=50, null=True, verbose_name="分值"
                    ),
                ),
            ],
            options={"verbose_name": "正能量搜索次数", "verbose_name_plural": "正能量搜索次数",},
        ),
    ]
