# Generated by Django 4.1.2 on 2022-10-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_goods_add_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="detail",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="料号说明"
            ),
        ),
    ]
