# Generated by Django 4.1.2 on 2022-10-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_alter_goods_ic_same"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="x2",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="小型包装型号2"
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="x1",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="小型包装型号"
            ),
        ),
    ]
