# Generated by Django 4.1.2 on 2022-10-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_goods_x2_alter_goods_x1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="total",
            field=models.IntegerField(
                blank=True, max_length=128, null=True, verbose_name="总分"
            ),
        ),
    ]
